import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "../components/home/Header";
import Footer from "../components/home/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
   <html
  lang="en"
  className={`${geistSans.variable} ${geistMono.variable} h-full`}
>
  <body
    className="min-h-screen flex flex-col antialiased"
  >

        {/* ✅ HEADER */}
        <Header />

        {/* ✅ MAIN CONTENT */}
    <main className="flex-1 w-full pt-16">
          {children}
        </main>

        {/* ✅ FOOTER */}
        <Footer />

      </body>
    </html>
  );
}



